enhancement:
  - head-branch: [^perf/, ^feat/, ^Feat/, ^FEAT/, ^Feature/, ^feature/, perf, feat, Feat, FEAT, Feature, feature]

workflow:
  - changed-files:
    - any-glob-to-any-file: ['.github/**']

bug:
  - head-branch: [^fix/, ^hotfix/,^bug/, ^Fix/, ^FIX/, ^Bug/, ^BUG/, fix, hotfix, bug, Fix, FIX, Bug, BUG]

documentation:
- changed-files:
  - any-glob-to-any-file: ['.docs/*', '**/*.md', 'README*']
