name: CD
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CD:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    container:
        image: archlinux
    steps:
      - name: Get required pacman pkgs
        shell: bash
        run: |
          sed -i 's/SigLevel = Required DatabaseOptional/SigLevel = Optional TrustAll/' /etc/pacman.conf
          pacman --noconfirm --noprogressbar -Syyu
          pacman --noconfirm --noprogressbar -Sy \
            git \
            diffutils \
            cmake \
            ninja \

      - uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Cmake
        run: cmake -B build -G Ninja

      - name: Ninja build
        run: ninja -C build

